apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-example
  namespace: priority-class
spec:
  hard:
    # pods: "3"
    requests.cpu: "2"
    requests.memory: "300Mi"
    limits.cpu: "4"
    limits.memory: "300Mi"
