apiVersion: batch/v1
kind: CronJob
metadata:
  name: history-limit-cronjob
spec:
  schedule: "*/1 * * * *"  # Run every 1 minutes
  successfulJobsHistoryLimit: 2  # Retain up to 2 successful Job completions
  failedJobsHistoryLimit: 1  # Retain only the latest failed Job completion
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: history-limit-container
            image: busybox
            command: ["echo", "Hello from the history-limit CronJob"]
          restartPolicy: Never
