apiVersion: v1
kind: Secret
metadata:
 name: app-secret
data:
 containers:
 - DB_Host: BsgascYTgf
   DB_User: HGsdhcTv
   DB_Password: HHGygdvcTY

Encrypt:
echo -n 'mysql' | base64

Decrypt:
echo -n 'sgvGDjhbD' | base64 --decode

kubectl create secret generic db-secret --from-literal=DB_Host=sql01 --from-literal=DB_User=root --from-literal=DB_Password=password123
