apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  signerName: kubernetes.io/kube-apiserver-client
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXlTYTJJZWdVTW52TXE1ZEUxaVNyaDhDcXh5TmRPM0h2dVVnemYxSThrUjBNCkI3c1RRVlJheE1JbHFwUFU0ZlNTOUJxNDZMcFZ3YnVzN2Q3OHNCSzlmZFI0UjN2ajBTdVpRTnFZTllpelczdW0KYjZjQ1FCZldQQjMvMk1kaVo0UXdYQUpNSXVYL0JVSGZtb3VMNHZrOGd1ektDNGJuU3RVWjhEUEIyMjVJSHhjbAowUWVhZjZ4bWUwSXVQNE5NTG1DWlQ1VmNsRFR3R2hYanlBSzgvNE5vay9YU0lPV2cyWThJc1JoV2gzaXd0SUZtCkJHKytkMVdvYklRMW1BZ0R2VDY2d2VXRVRIeG5nLzgzYXhUWTFOTHA5Z0UvK3h5cDJZU2tsemViLytVSFY4OWMKRDVGZ2VIdEJib1VDaXMyS3RNQ0FmZ2NRb2lEZXd1aDFYU0JYRm41Ly9RSURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBQnU5cExCUk9NdmIxL01ubys1dnNRNGxTbXFKU2pNTS9CZFM2Q1ptcVZ1LzIwTVhPSzkrCk83RzhsRlRIVGhoSEJSdUppK3hla1pqTzhlTGdYTWNmTWFyM3d6dEhhSTZ5d2RiaVk2TWE3cmo2WXU2dGNFN0QKbllNeGhPbi9HdXdpQURkbWFrYVhXeUlscVFXeTJGNGdmaDhQMnliMXVaazFjSktyNjhaMVB6dW1sNGdDOWJBbgp4KzFyV1RZYXBUZ1hOeDhCYzhITldTSDFEOU5xQlpnaE13azlDNnBDYURqbXh3VGc0enNZaWxESGJTaGR4azV5ClhVcnVlYng2ZyszUEQ5c0dETU9HQ3dTWUltb1VlKzZDS0lrWnJnZ3MxMHlJbzNndjVNVnVSMmEvVG1LdTdOWVoKWFFjOVNHUVo1K09WdXhja1N3azJXcE94aUl0VnljWk5lNXM9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
