apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim-rom
spec:
  storageClassName: my-own-sc
  accessModes:
    - ReadOnlyMany # the volume can be mounted as read-only by many nodes.
  resources:
    requests:
      storage: 1Gi
