apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-pod-identity-demo
  region: us-west-2
  version: "1.28"
addons:
  - name: vpc-cni
  - name: coredns
  - name: kube-proxy
  - name: eks-pod-identity-agent  # Critical for Pod Identity
managedNodeGroups:
  - name: eks-shared-demo-mng
    instanceType: t3.medium
    privateNetworking: true
    minSize: 2
    desiredCapacity: 2
    maxSize: 5
