apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-first-externalsecret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretstore
    kind: SecretStore
  target:
    name: aws-sm-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: My-First-SM-Secret
