apiVersion: apps/v1
kind: Deployment
metadata:
  name: tcp-startup-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tcp-nginx
  template:
    metadata:
      labels:
        app: tcp-nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        startupProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 5
