# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      - system:node-proxier
      rolearn: arn:aws:iam::124567890:role/EKSFargatePodExecutionRole-CF-my-eks-fargate-cluster
      username: system:node:{{SessionName}}
    - rolearn: arn:aws:iam::124567890:role/ec2-eks-admin-role
      username: bastionuser
      groups:
      - system:masters
  mapUsers: |
    - userarn: arn:aws:iam::124567890:user/test
      username: test
      groups:
      - system:bootstrappers
      - system:masters
      - system:nodes
      - eks-console-dashboard-full-access-group
kind: ConfigMap
metadata:
  creationTimestamp: "2024-08-07T00:08:35Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "10222"
  uid: 152a1a06-3039-4969-9b44-f97707430bf5
