apiVersion: v1
kind: Pod
metadata:
  name: simple
  labels:
    name: simple
spec:
  containers:
  - name: simple
    image: simple-webapp-color
    ports":
      - containerPort: 8080
    envFrom:
      - configMapRef:
           name: app-config
