allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-own-delete-sc
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Delete # Deletion removes both the PersistentVolume object from Kubernetes, as well as the associated storage asset in the external infrastructure. 
volumeBindingMode: Immediate
