allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-own-recucle-sc
provisioner: dobs.csi.digitalocean.com
reclaimPolicy: Recycle # The Recycle reclaim policy is deprecated. Instead, the recommended approach is to use dynamic provisioning.
volumeBindingMode: Immediate
