apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-02-27T16:49:05Z"
  labels:
    name: webapp-color
  name: webapp-color
  namespace: default
  resourceVersion: "1266"
  selfLink: /api/v1/namespaces/default/pods/webapp-color
  uid: a2c5c23b-47bc-4877-a172-7b1285ca298d
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: pink
    image: kodekloud/webapp-color
    imagePullPolicy: Always
    name: webapp-color
