apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/anveshmuppeda/argo-cd-demo
    targetRevision: HEAD
    path: prod

  destination: 
    name: prod
    namespace: argocd-demo

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
