apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
spec:
  containers:
  #App container
  - name: nginx-container
    image: nginx:latest
    ports:
      - containerPort: 80
    volumeMounts:
      - name: logs
        mountPath: /var/log/nginx
  #This si extra container
  - name: sidecar-container
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 1000"]
    volumeMounts:
      - name: logs
        mountPath: /var/log/nginx
  volumes:
    - name: logs
      emptyDir: {}
    #kubectl debug -it test --image=busybox:1.28 --target=test
    #kubectl debug test -it --image=busybox:1.28 --share-processes --copy-to=debug
